name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test_and_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # adapte si besoin

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint coverage sphinx sphinx-rtd-theme

      - name: Run unit tests with coverage
        run: |
          coverage run -m unittest discover -s tests
          coverage report -m
          coverage xml

      - name: Check pylint score
        run: |
          pylint src/ > pylint_report.txt || true
          score=$(pylint src/ | grep "Your code has been rated at" | awk '{print $7}' | cut -d/ -f1)
          echo "Pylint score: $score"
          if (( $(echo "$score < 9.0" | bc -l) )); then
            echo "Pylint score is less than 9.0, failing."
            exit 1
          fi

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

  deploy_docs:
    needs: test_and_lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Déploie docs uniquement sur main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies for docs
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme

      - name: Build Sphinx docs
        run: |
          cd docs
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
